---
- name: 'Install Apache base configuration'
  template:
    src: templates/apache/httpd.conf
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: apache
    mode: 0640
  notify: 'Restart Apache'

- name: 'Install Apache module configuration'
  template:
    src: templates/apache/00-base.conf
    dest: /etc/httpd/conf.modules.d/00-base.conf
    owner: root
    group: apache
    mode: 0640
  notify: 'Restart Apache'

- name: 'Remove unused configuration'
  template:
    src: templates/apache/config-blocker.conf
    dest: '/etc/httpd/{{ item }}'
    owner: root
    group: apache
    mode: 0640
  with_items:
    - conf.d/ssl.conf
    - conf.d/welcome.conf
    - conf.d/autoindex.conf
    - conf.d/userdir.conf
    - conf.modules.d/00-dav.conf
    - conf.modules.d/00-lua.conf
    - conf.modules.d/00-mpm.conf
    - conf.modules.d/00-proxy.conf
    - conf.modules.d/00-ssl.conf
    - conf.modules.d/00-systemd.conf
    - conf.modules.d/01-cgi.conf

- name: 'Install Apache configuration'
  template:
    src: templates/apache/idp.conf
    dest: '/etc/httpd/conf.d/idp.conf'
    owner: root
    group: apache
    mode: 0640
  notify: 'Restart Apache'

- name: 'Create keypair directory'
  file:
    name: '/opt/keypairs'
    state: directory
    owner: root
    group: root
    mode: 0700

- name: 'Install Apache SSL keys'
  copy:
    src: 'assets/{{inventory_hostname}}/apache/{{ item }}'
    dest: '/opt/keypairs/{{ item }}'
    owner: root
    group: apache
    mode: 0640
  with_items:
    - server.crt
    - server.key
    - intermediate.crt
  notify: 'Restart Apache'

- name: 'Enable firewalld'
  service: name=firewalld state=started enabled=yes

- name: 'Open Apache firewall ports'
  firewalld:
    port: '{{ item }}'
    state: enabled
    permanent: yes
  with_items:
    - 443/tcp
  register: firewall

- name: 'Restart firewalld'
  service: name=firewalld state=restarted enabled=yes
  when: firewall | changed

- meta: flush_handlers

- name: 'Enable Apache service'
  service: name=httpd state=started enabled=yes

