---
- name: 'Create MariaDB directories'
  file:
    dest: '{{ item }}'
    state: directory
    owner: mysql
    group: mysql
    mode: 0700
  with_items:
    - /var/lib/mysql
    - /var/lib/mysql/tmp
    - /var/lib/mysql/binlog

- name: 'Create /var/run/mariadb'
  file:
    dest: /var/run/mariadb
    state: directory
    owner: mysql
    group: mysql
    mode: 0700

- name: 'Start database server'
  service:
    name: mariadb
    state: started
    enabled: yes

- name: 'Create lock_down_db.sql'
  template:
    src: templates/db/lock_down_db.sql
    dest: /root/lock_down_db.sql
    owner: root
    group: root
    mode: 0600
  register: security_sql

- name: 'Run lock_down_db.sql'
  command: 'mysql -e "source /root/lock_down_db.sql"'
  when: security_sql | changed

- name: 'Write /root/.my.cnf'
  template:
    src: templates/db/dot-my.cnf
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- name: 'Create application database'
  mysql_db:
    login_unix_socket: /var/lib/mysql/mysql.sock
    name: '{{ db.name }}'
    collation: utf8_general_ci
    encoding: utf8
    state: present

